angular.
module('frontendApp',[
	'ngRoute',
	'angular.filter',
	'ngSanitize',
	'markdown',
	'xeditable',
	'checklist-model',
	'sharedAssets',
	'frontendClasses',
	'frontendEvents',
	'frontendCancellation',
	'backendApp',
	'cloudinary'
]);
